# Site/SEO settings
email: dergigi@pm.me
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics:

name: Gigi
title: 21 Lessons
description: >
  21 Lessons Learned from Falling Down the Bitcoin Rabbit Hole.
url: https://21lessons.com
twitter_username: dergigi
default_img: /assets/images/avatar.jpg
social:
  - name: twitter
    url: https://twitter.com/dergigi
  - name: instagram
    url: https://www.instagram.com/dergigi/
  - name: github
    url: https://github.com/dergigi
  - name: medium
    url: https://medium.com/@dergigi
  - name: bitcoin
    url: https://dergigi.com/support

# Collections
collections:
  lessons:
    output: true
    permalink: /:path # path = filename relative

# Author settings
author:
  - name: Gigi
    bio: Bio as in biological?
    url: https://dergigi.com/contact

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - env
  - scripts
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
